<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Area Rankings Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }
        .header h1 {
            margin: 0;
            color: #333;
            font-size: 24px;
        }
        .header .subtitle {
            color: #666;
            margin-top: 5px;
        }
        .report-info {
            margin-bottom: 20px;
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
        }
        .report-info table {
            width: 100%;
            border-collapse: collapse;
        }
        .report-info td {
            padding: 5px 10px;
            border: none;
        }
        .report-info .label {
            font-weight: bold;
            width: 150px;
        }
        .rankings-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        .rankings-table th,
        .rankings-table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        .rankings-table th {
            background-color: #f2f2f2;
            font-weight: bold;
            text-align: center;
        }
        .rankings-table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .rank-position {
            text-align: center;
            font-weight: bold;
            font-size: 14px;
        }
        .rank-1 { color: #FFD700; }
        .rank-2 { color: #C0C0C0; }
        .rank-3 { color: #CD7F32; }
        .score {
            text-align: center;
        }
        .percentage {
            text-align: center;
        }
        .summary-stats {
            margin-top: 30px;
            display: flex;
            justify-content: space-around;
        }
        .stat-box {
            text-align: center;
            padding: 15px;
            background-color: #f8f9fa;
            border-radius: 5px;
            min-width: 120px;
        }
        .stat-box .number {
            font-size: 24px;
            font-weight: bold;
            color: #007bff;
        }
        .stat-box .label {
            font-size: 12px;
            color: #666;
            margin-top: 5px;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .page-break {
            page-break-before: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Area Rankings Report</h1>
        <div class="subtitle">
            {{ $format === 'detailed' ? 'Detailed Analysis' : 'Summary Report' }}
        </div>
    </div>

    <div class="report-info">
        <table>
            <tr>
                <td class="label">Report Period:</td>
                <td>{{ ucfirst($period) }} {{ $period !== 'all' ? '(' . now()->format('Y-m') . ')' : '' }}</td>
                <td class="label">Generated On:</td>
                <td>{{ $generated_at->format('F j, Y \a\t g:i A') }}</td>
            </tr>
            <tr>
                <td class="label">College Filter:</td>
                <td>{{ $college ? $college->name : 'All Colleges' }}</td>
                <td class="label">Generated By:</td>
                <td>{{ $generated_by }}</td>
            </tr>
            <tr>
                <td class="label">Area Filter:</td>
                <td>{{ $area ? $area->name : 'All Areas' }}</td>
                <td class="label">Total Records:</td>
                <td>{{ $rankings->count() }}</td>
            </tr>
        </table>
    </div>

    @if($rankings->count() > 0)
        <table class="rankings-table">
            <thead>
                <tr>
                    <th style="width: 8%">Rank</th>
                    <th style="width: 25%">College</th>
                    <th style="width: 20%">Area</th>
                    <th style="width: 12%">Completion %</th>
                    <th style="width: 10%">Quality Score</th>
                    <th style="width: 12%">Accreditor Rating</th>
                    <th style="width: 13%">Weighted Score</th>
                    @if($format === 'detailed')
                        <th style="width: 8%">Parameters</th>
                        <th style="width: 8%">SWOT Status</th>
                    @endif
                </tr>
            </thead>
            <tbody>
                @foreach($rankings as $ranking)
                    <tr>
                        <td class="rank-position rank-{{ min($ranking->rank_position, 3) }}">
                            #{{ $ranking->rank_position }}
                        </td>
                        <td>{{ $ranking->college->name }}</td>
                        <td>{{ $ranking->area->name }}</td>
                        <td class="percentage">{{ number_format($ranking->completion_percentage, 1) }}%</td>
                        <td class="score">{{ number_format($ranking->quality_score, 2) }}</td>
                        <td class="score">{{ number_format($ranking->accreditor_rating, 2) }}</td>
                        <td class="score">{{ number_format($ranking->weighted_score, 2) }}</td>
                        @if($format === 'detailed')
                            <td class="score">{{ $ranking->completed_parameters }}/{{ $ranking->total_parameters }}</td>
                            <td class="score">{{ $ranking->approved_swot_count }}/{{ $ranking->approved_swot_count + $ranking->rejected_swot_count }}</td>
                        @endif
                    </tr>
                @endforeach
            </tbody>
        </table>

        @if($format === 'detailed')
            <div class="page-break"></div>
            <h2>Detailed Analysis</h2>
            
            @php
                $avgCompletion = $rankings->avg('completion_percentage');
                $avgQuality = $rankings->avg('quality_score');
                $avgRating = $rankings->avg('accreditor_rating');
                $totalParameters = $rankings->sum('total_parameters');
                $completedParameters = $rankings->sum('completed_parameters');
            @endphp

            <div class="summary-stats">
                <div class="stat-box">
                    <div class="number">{{ number_format($avgCompletion, 1) }}%</div>
                    <div class="label">Average Completion</div>
                </div>
                <div class="stat-box">
                    <div class="number">{{ number_format($avgQuality, 2) }}</div>
                    <div class="label">Average Quality</div>
                </div>
                <div class="stat-box">
                    <div class="number">{{ number_format($avgRating, 2) }}</div>
                    <div class="label">Average Rating</div>
                </div>
                <div class="stat-box">
                    <div class="number">{{ $completedParameters }}/{{ $totalParameters }}</div>
                    <div class="label">Total Parameters</div>
                </div>
            </div>

            <h3>Top Performers</h3>
            <table class="rankings-table">
                <thead>
                    <tr>
                        <th>Rank</th>
                        <th>College - Area</th>
                        <th>Weighted Score</th>
                        <th>Key Metrics</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($rankings->take(5) as $ranking)
                        <tr>
                            <td class="rank-position">#{{ $ranking->rank_position }}</td>
                            <td>{{ $ranking->college->name }} - {{ $ranking->area->name }}</td>
                            <td class="score">{{ number_format($ranking->weighted_score, 2) }}</td>
                            <td>
                                Completion: {{ number_format($ranking->completion_percentage, 1) }}%<br>
                                Quality: {{ number_format($ranking->quality_score, 2) }}<br>
                                Rating: {{ number_format($ranking->accreditor_rating, 2) }}
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @endif
    @else
        <div style="text-align: center; padding: 50px; color: #666;">
            <h3>No ranking data available</h3>
            <p>No rankings found for the selected criteria.</p>
        </div>
    @endif

    <div class="footer">
        <p>This report was generated automatically by the Accreditation Management System.</p>
        <p>Report ID: {{ md5($generated_at . $generated_by) }} | Generated: {{ $generated_at->format('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>